### PR TITLE
[FIXED JENKINS-18972] use scriptler GroovyScript to run scriptlers

### PR DESCRIPTION
**Pull request by ndeloof**
scriptler GroovyScript set parent classloader, that allow access to jenkins model when ran on master

### CODE REVIEW

**Comment by jglick** [comment]
What does “when run on master” mean? Surely parameter evaluation _always_ runs on the master?

**Comment by ndeloof** [comment]
dynamic parameter plugin offer option to run script on remote. Didn't checked how this is actually implemented

**Comment by kesor** [comment]
:+1: Please merge this into a release, will make it so much easier to script parameters using existing installed plugins (like git-client).

For example, something that doesn't work because a complex classpath must be provided as the plugin doesn't use GroovyScript:

``` groovy
org.jenkinsci.plugins.gitclient.Git.with(null, null)
.using("/usr/bin/git")
.getClient()
.getHeadRev("https://github.com/rails/rails")
.collect {
  it.getKey().replace("refs/heads/","")
}
```

**Comment by ulich** [comment]
what is the status here? I would like to have this feature merged. Can i contribute in some way?

Edit: I found out that the https://wiki.jenkins-ci.org/display/JENKINS/Active+Choices+Plugin supports this

**Comment by pupssman** [comment]
@ndeloof is there a way to merge this to main repo?

**Comment by ndeloof** [comment]
inactive, feel free to take over

**Pull request closed without merging**
